# Generated by Django 5.1.2 on 2024-11-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_project_video_url_project_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_file',
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
