# Generated by Django 5.1.2 on 2024-11-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_project_video_file_project_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('categories', models.ManyToManyField(related_name='services', to='main.category', verbose_name='Категории услуг')),
            ],
        ),
    ]
